name: Alpha Release

on:
  push:
    branches:
      - alpha
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::649614366484:role/github-actions
          aws-region: us-east-1
      - name: Configure npm with CodeArtifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain applyboard-repository-manager --domain-owner 649614366484 --query authorizationToken --output text`
              echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
          npm config set //applyboard-repository-manager-649614366484.d.codeartifact.us-east-1.amazonaws.com/npm/applyboard-npm/:_authToken=${CODEARTIFACT_AUTH_TOKEN}
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm run test:cov
      - name: Short Sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Alpha release
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          npm version 0.0.0-ALPHA.$SHORT_SHA --no-git-tag-version
          npm publish --tag ALPHA.$SHORT_SHA
          echo "Install the Alpha release on a consumer project for testing." >> $GITHUB_STEP_SUMMARY
          echo "> npm install @applyboard/cdk-constructs@ALPHA.$SHORT_SHA" >> $GITHUB_STEP_SUMMARY